name: Generate Wrapper & Build APK (No Local PC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Maturin
        run: pip install maturin

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use project-local Gradle cache
        run: echo "GRADLE_USER_HOME=$GITHUB_WORKSPACE/.gradle" >> $GITHUB_ENV

      - name: Clear possibly corrupt Gradle jars cache
        run: rm -rf ~/.gradle/caches/jars-9 || true

      - name: Download Gradle 8.13 temporarily
        run: wget https://services.gradle.org/distributions/gradle-8.13-bin.zip -O gradle-8.13-bin.zip

      - name: Unzip temporary Gradle
        run: unzip -q gradle-8.13-bin.zip

      - name: Generate project's Gradle Wrapper files
        run: ./gradle-8.13/bin/gradle wrapper --gradle-version 8.13 --distribution-type all

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK with Gradle Wrapper
        run: ./gradlew assembleDebug
        # --- هذا هو الجزء المهم الذي يحل مشكلة المصادقة مع JitPack ---
        env:
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
         name: oneui-debug-apk
         path: app/build/outputs/apk/debug/app-debug.apk
